Revert "rde: emacs-completion: Replace consult-find args with fd."
fd fails with:

error: Found argument '-n' which wasn't expected, or isn't valid in this context

This reverts commit 560f31c4663447b0254e800a67af6581fe5dcbf5.